//! Golden-vector tests against fixtures generated by
//! `tools/gen_fixtures.py` (numpy/scipy — an independent implementation
//! of the same math). Regenerate with:  `python3 tools/gen_fixtures.py`

use oxideq::dsp::EqChain;
use oxideq::preset::{Band, FilterKind, Preset};
use oxideq::resample::{Upsampler2x, halfband_taps};

fn fixture(name: &str) -> Vec<f64> {
    let path = format!("{}/tests/data/{name}", env!("CARGO_MANIFEST_DIR"));
    let bytes =
        std::fs::read(&path).unwrap_or_else(|e| panic!("{path}: {e} — run tools/gen_fixtures.py"));
    bytes
        .chunks_exact(8)
        .map(|c| f64::from_le_bytes(c.try_into().expect("8-byte chunk")))
        .collect()
}

fn golden_preset() -> Preset {
    Preset {
        preamp_db: -3.0,
        bands: vec![
            Band {
                kind: FilterKind::Peaking,
                fc_hz: 1_000.0,
                gain_db: 6.0,
                q: 1.0,
            },
            Band {
                kind: FilterKind::Peaking,
                fc_hz: 8_000.0,
                gain_db: -4.0,
                q: 2.0,
            },
        ],
    }
}

fn assert_close(ours: &[f64], golden: &[f64], tol: f64, what: &str) {
    assert_eq!(ours.len(), golden.len(), "{what}: length");
    for (i, (a, b)) in ours.iter().zip(golden).enumerate() {
        assert!((a - b).abs() < tol, "{what}: sample {i}: {a} vs golden {b}");
    }
}

#[test]
fn taps_match_scipy_firwin() {
    for fs in [44_100.0, 48_000.0, 88_200.0, 96_000.0] {
        let ours = halfband_taps(fs, 20_000.0, 120.0);
        let golden = fixture(&format!("hb_taps_{}.f64", fs as u32));
        assert_close(&ours, &golden, 1e-14, &format!("taps @ {fs}"));
    }
}

#[test]
fn upsampler_matches_scipy_upfirdn() {
    let taps = halfband_taps(48_000.0, 20_000.0, 120.0);
    let input = fixture("up2x_in.f64");
    let golden = fixture("up2x_out_48000.f64");
    let mut up = Upsampler2x::new(&taps);
    let ours: Vec<f64> = input.iter().flat_map(|&x| up.push(x)).collect();
    assert_close(&ours, &golden, 1e-12, "up2x waveform");
}

#[test]
fn eq_waveform_matches_scipy_lfilter() {
    let input = fixture("eq_in.f64");
    let golden = fixture("eq_out_48000_1x.f64");
    let mut buf: Vec<f32> = input.iter().map(|&x| x as f32).collect();
    let mut chain = EqChain::new(&golden_preset(), 48_000.0, 1, 1).unwrap();
    chain.process(&mut buf);
    let ours: Vec<f64> = buf.iter().map(|&x| f64::from(x)).collect();
    // f32 boundary + DF1-vs-DF2T rounding: 1e-6 abs still catches any
    // real coefficient or plumbing bug by orders of magnitude.
    assert_close(&ours, &golden, 1e-6, "EQ 1x waveform");
}

#[test]
fn oversampled_chain_matches_scipy_end_to_end() {
    let input = fixture("eq_in.f64");
    let golden = fixture("eq_out_44100_4x.f64");
    let mut buf: Vec<f32> = input.iter().map(|&x| x as f32).collect();
    let mut chain = EqChain::new(&golden_preset(), 44_100.0, 1, 4).unwrap();
    chain.process(&mut buf);
    let ours: Vec<f64> = buf.iter().map(|&x| f64::from(x)).collect();
    assert_close(&ours, &golden, 1e-6, "EQ 4x waveform");
}
