//! PipeWire routing: Tier 1 virtual-sink install and (Task 9) Tier 3
//! pw-link auto-wiring. Pure helpers are testable on any OS; command
//! execution only makes sense on Linux with PipeWire.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

pub const SINK_NODE: &str = "OxidEQ-Sink";

/// PipeWire drop-in creating the virtual sink users select as their
/// default output (Tier 1). OxidEQ captures the sink's monitor.
pub fn sink_config() -> String {
    format!(
        r#"# Generated by `oxideq install-sink`.
# Select "OxidEQ Sink" as the default output device; run `oxideq run …`
# to EQ it into your DAC. Remove this file to uninstall.
context.objects = [
    {{   factory = adapter
        args = {{
            factory.name     = support.null-audio-sink
            node.name        = "{SINK_NODE}"
            node.description = "OxidEQ Sink"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            monitor.channel-volumes = true
        }}
    }}
]
"#
    )
}

pub fn config_path(home: &Path, xdg_config: Option<&Path>) -> PathBuf {
    let base = xdg_config
        .map(Path::to_path_buf)
        .unwrap_or_else(|| home.join(".config"));
    base.join("pipewire/pipewire.conf.d/99-oxideq-sink.conf")
}

pub fn install_sink() -> Result<()> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    let xdg = std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from);
    let path = config_path(&home, xdg.as_deref());
    let dir = path.parent().expect("config path always has a parent");
    fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    fs::write(&path, sink_config()).with_context(|| format!("writing {}", path.display()))?;
    println!("wrote {}", path.display());
    println!("activate:  systemctl --user restart pipewire pipewire-pulse");
    println!("then pick \"OxidEQ Sink\" as the default output device.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn sink_config_defines_a_null_sink_named_oxideq() {
        let c = sink_config();
        assert!(c.contains("support.null-audio-sink"));
        assert!(c.contains(&format!("node.name        = \"{SINK_NODE}\"")));
        assert!(c.contains("media.class      = Audio/Sink"));
        assert!(c.contains("[ FL FR ]"));
    }

    #[test]
    fn config_path_defaults_to_dot_config() {
        let p = config_path(Path::new("/home/u"), None);
        assert_eq!(
            p,
            Path::new("/home/u/.config/pipewire/pipewire.conf.d/99-oxideq-sink.conf")
        );
    }

    #[test]
    fn config_path_honors_xdg_config_home() {
        let p = config_path(Path::new("/home/u"), Some(Path::new("/xdg")));
        assert_eq!(
            p,
            Path::new("/xdg/pipewire/pipewire.conf.d/99-oxideq-sink.conf")
        );
    }
}
