//! PipeWire routing: Tier 1 virtual-sink install and (Task 9) Tier 3
//! pw-link auto-wiring. Pure helpers are testable on any OS; command
//! execution only makes sense on Linux with PipeWire.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Duration;

use anyhow::{bail, Context, Result};

pub const SINK_NODE: &str = "OxidEQ-Sink";

/// PipeWire drop-in creating the virtual sink users select as their
/// default output (Tier 1). OxidEQ captures the sink's monitor.
pub fn sink_config() -> String {
    format!(
        r#"# Generated by `oxideq install-sink`.
# Select "OxidEQ Sink" as the default output device; run `oxideq run …`
# to EQ it into your DAC. Remove this file to uninstall.
context.objects = [
    {{   factory = adapter
        args = {{
            factory.name     = support.null-audio-sink
            node.name        = "{SINK_NODE}"
            node.description = "OxidEQ Sink"
            media.class      = Audio/Sink
            audio.position   = [ FL FR ]
            monitor.channel-volumes = true
        }}
    }}
]
"#
    )
}

pub fn config_path(home: &Path, xdg_config: Option<&Path>) -> PathBuf {
    let base = xdg_config
        .map(Path::to_path_buf)
        .unwrap_or_else(|| home.join(".config"));
    base.join("pipewire/pipewire.conf.d/99-oxideq-sink.conf")
}

pub fn install_sink() -> Result<()> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .context("HOME is not set")?;
    let xdg = std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from);
    let path = config_path(&home, xdg.as_deref());
    let dir = path.parent().expect("config path always has a parent");
    fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    fs::write(&path, sink_config()).with_context(|| format!("writing {}", path.display()))?;
    println!("wrote {}", path.display());
    println!("activate:  systemctl --user restart pipewire pipewire-pulse");
    println!("then pick \"OxidEQ Sink\" as the default output device.");
    Ok(())
}

/// Filter a `pw-link -o` / `pw-link -i` listing (one `node:port` per line)
/// to ports whose *node* name contains `node_substr`, case-insensitively.
/// Sorted, so FL precedes FR and zips align across nodes.
pub fn matching_ports<'a>(listing: &'a str, node_substr: &str) -> Vec<&'a str> {
    let needle = node_substr.to_lowercase();
    let mut ports: Vec<&str> = listing
        .lines()
        .map(str::trim)
        .filter(|line| {
            line.split(':')
                .next()
                .is_some_and(|node| node.to_lowercase().contains(&needle))
        })
        .collect();
    ports.sort_unstable();
    ports
}

/// Tier 3: wire `OxidEQ-Sink → oxideq → dac` with pw-link, then cut any
/// feedback links from our playback back into the OxidEQ sink (PipeWire
/// auto-connects new streams to the default sink — which may be ours).
pub fn auto_link(dac_substr: Option<&str>) -> Result<()> {
    for _ in 0..20 {
        std::thread::sleep(Duration::from_millis(250));
        let outs = pw_link_list("-o")?;
        let ins = pw_link_list("-i")?;
        let sink_monitor = matching_ports(&outs, SINK_NODE);
        let our_capture = matching_ports(&ins, "oxideq");
        let our_playback = matching_ports(&outs, "oxideq");
        if sink_monitor.len() < 2 || our_capture.len() < 2 || our_playback.len() < 2 {
            continue; // streams not in the graph yet — retry
        }
        for (from, to) in sink_monitor.iter().zip(&our_capture) {
            link(from, to)?;
        }
        match dac_substr {
            Some(dac) => {
                let dac_inputs: Vec<&str> = matching_ports(&ins, dac)
                    .into_iter()
                    .filter(|p| !p.to_lowercase().contains("oxideq"))
                    .collect();
                if dac_inputs.len() < 2 {
                    bail!("output device {dac:?} has no ports in the PipeWire graph");
                }
                for (from, to) in our_playback.iter().zip(&dac_inputs) {
                    link(from, to)?;
                }
            }
            None => eprintln!("auto-link: no --output given; playback stays on the default target"),
        }
        unlink_feedback(&our_playback);
        println!("auto-link: wired {SINK_NODE} → oxideq → output");
        return Ok(());
    }
    bail!("auto-link: ports never appeared (need pw-link, the OxidEQ sink, and running streams)")
}

fn pw_link_list(flag: &str) -> Result<String> {
    let out = Command::new("pw-link")
        .arg(flag)
        .output()
        .context("running pw-link (is pipewire-utils installed?)")?;
    Ok(String::from_utf8_lossy(&out.stdout).into_owned())
}

fn link(from: &str, to: &str) -> Result<()> {
    // Non-zero exit for an already-existing link is fine — ignore status.
    Command::new("pw-link")
        .args([from, to])
        .status()
        .context("running pw-link")?;
    Ok(())
}

/// Best-effort: cut playback→own-sink links that would howl.
fn unlink_feedback(our_playback: &[&str]) {
    for (port, chan) in our_playback.iter().zip(["FL", "FR"]) {
        let _ = Command::new("pw-link")
            .args(["-d", port, &format!("{SINK_NODE}:playback_{chan}")])
            .status();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn sink_config_defines_a_null_sink_named_oxideq() {
        let c = sink_config();
        assert!(c.contains("support.null-audio-sink"));
        assert!(c.contains(&format!("node.name        = \"{SINK_NODE}\"")));
        assert!(c.contains("media.class      = Audio/Sink"));
        assert!(c.contains("[ FL FR ]"));
    }

    #[test]
    fn config_path_defaults_to_dot_config() {
        let p = config_path(Path::new("/home/u"), None);
        assert_eq!(
            p,
            Path::new("/home/u/.config/pipewire/pipewire.conf.d/99-oxideq-sink.conf")
        );
    }

    #[test]
    fn config_path_honors_xdg_config_home() {
        let p = config_path(Path::new("/home/u"), Some(Path::new("/xdg")));
        assert_eq!(
            p,
            Path::new("/xdg/pipewire/pipewire.conf.d/99-oxideq-sink.conf")
        );
    }

    const LISTING: &str = "\
OxidEQ-Sink:monitor_FL
OxidEQ-Sink:monitor_FR
alsa_output.usb-DAC:playback_FL
alsa_output.usb-DAC:playback_FR
oxideq:input_FL
oxideq:input_FR
Firefox:output_FL
";

    #[test]
    fn matching_ports_filters_by_node_case_insensitively() {
        assert_eq!(
            matching_ports(LISTING, "oxideq-sink"),
            vec!["OxidEQ-Sink:monitor_FL", "OxidEQ-Sink:monitor_FR"]
        );
        assert_eq!(
            matching_ports(LISTING, "usb-DAC"),
            vec![
                "alsa_output.usb-DAC:playback_FL",
                "alsa_output.usb-DAC:playback_FR"
            ]
        );
    }

    #[test]
    fn matching_ports_is_sorted_fl_before_fr() {
        // Reversed input order must still come out FL, FR.
        let reversed = "oxideq:input_FR\noxideq:input_FL\n";
        assert_eq!(
            matching_ports(reversed, "oxideq"),
            vec!["oxideq:input_FL", "oxideq:input_FR"]
        );
    }

    #[test]
    fn matching_ports_matches_node_not_port_text() {
        // "monitor" appears in OxidEQ-Sink's *port* names only — a node
        // filter for "monitor" must not match them.
        assert!(matching_ports(LISTING, "monitor").is_empty());
    }
}
